# Generated by Django 3.1.6 on 2021-02-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('syllabus', models.FileField(upload_to='syllabus/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('lecturer', models.CharField(max_length=32)),
                ('capacity', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course_group')),
            ],
        ),
    ]
