# Generated by Django 3.1.6 on 2021-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_group',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
