# Generated by Django 3.1.6 on 2021-02-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210214_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group', to='api.course_group'),
        ),
        migrations.AlterField(
            model_name='course_group',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_group', models.ManyToManyField(to='api.Course_group')),
            ],
        ),
    ]
