# Generated by Django 3.1.6 on 2021-02-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210218_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
