# Generated by Django 3.1.6 on 2021-02-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.course_group'),
        ),
    ]
