# Generated by Django 3.1.6 on 2021-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_group',
            name='is_elective',
            field=models.BooleanField(default=True),
        ),
    ]
