# Generated by Django 3.1.6 on 2021-03-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210318_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.office'),
        ),
    ]
