# Generated by Django 3.1.6 on 2021-03-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_student_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_group',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.office'),
        ),
    ]
