# Generated by Django 3.1.6 on 2021-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_group',
            name='syllabus',
            field=models.FileField(null=True, upload_to='syllabus/'),
        ),
    ]
