# Generated by Django 3.1.6 on 2021-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210521_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_group',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
