# Generated by Django 3.1.6 on 2021-06-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210521_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('course', 'student')},
        ),
        migrations.AlterIndexTogether(
            name='ranking',
            index_together={('course', 'student')},
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='course_group',
        ),
    ]
