# Generated by Django 4.2.2 on 2023-06-22 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210612_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='תעודת הזהות חייבת להיות 9 ספרות', regex='^.{9}$')]),
        ),
    ]
