# Generated by Django 4.2.2 on 2023-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount_elective',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='api.course'),
        ),
    ]
