# Generated by Django 4.2.2 on 2023-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.IntegerField(null=True),
        ),
    ]
