# Generated by Django 4.2.2 on 2023-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_course_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.AddField(
            model_name='course_group',
            name='groups',
            field=models.IntegerField(null=True),
        ),
    ]
