# Generated by Django 3.1.6 on 2023-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20230720_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, choices=[('1', 'BASIC'), ('2', 'EXCELLENCE')], default='1', max_length=2, null=True),
        ),
    ]
