# Generated by Django 3.1.6 on 2023-07-31 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20230725_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=123456789, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='תעודת הזהות חייבת להיות 9 ספרות', regex='^.{9}$')]),
            preserve_default=False,
        ),
    ]
